# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-12 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True, verbose_name='Record created')),
                ('record_modified', models.DateTimeField(auto_now=True, verbose_name='Record modified')),
                ('train_data_url', models.URLField(verbose_name='Train data URL')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=100)),
                ('model_path', models.FilePathField(default='/Users/alex/work/yrunner/templates/nt_weights', verbose_name='Model path')),
                ('log', models.TextField(default='', verbose_name='Log')),
            ],
        ),
    ]
