# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-22 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Class name')),
                ('belong_to_class_question', models.TextField(blank=True, null=True, verbose_name='The question of belonging to a class')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Class question')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Service Number')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTagBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_order', models.IntegerField(verbose_name='Priority Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_binding', to='alesya.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='alesya.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='servicetagbinding',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_binding', to='alesya.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetagbinding',
            unique_together=set([('service', 'tag')]),
        ),
    ]
