# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifierTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Class item name')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Service Number')),
                ('name', models.CharField(max_length=100, verbose_name='Service name')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='Project number')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='alesya.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EntityClassifierTagBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_order', models.IntegerField(verbose_name='Priority Order')),
                ('classifier_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_binding', to='alesya.ClassifierTag')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifier_tags_binding', to='alesya.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityTagBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_order', models.IntegerField(verbose_name='Priority Order')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_binding', to='alesya.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='alesya.Location', verbose_name='Child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='alesya.Location', verbose_name='Parent')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Сlassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Class name')),
                ('belong_to_class_question', models.TextField(blank=True, null=True, verbose_name='The question of belonging to a class')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Class question')),
            ],
        ),
        migrations.AddField(
            model_name='entitytagbinding',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities_binding', to='alesya.Tag'),
        ),
        migrations.AddField(
            model_name='classifiertag',
            name='classifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alesya.Сlassifier', verbose_name='Classifier'),
        ),
        migrations.AlterUniqueTogether(
            name='locationbinding',
            unique_together=set([('child', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='entitytagbinding',
            unique_together=set([('entity', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='entityclassifiertagbinding',
            unique_together=set([('entity', 'classifier_tag')]),
        ),
    ]
