# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alesya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiertag',
            name='classifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alesya.Сlassifier', verbose_name='Classifier'),
        ),
    ]
