# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-23 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alesya', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classification',
            new_name='Entity',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='classification',
            new_name='entity',
        ),
    ]
