# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alesya', '0002_auto_20180223_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project number'),
        ),
    ]
