# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alesya', '0003_service_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='alesya.Entity'),
        ),
    ]
