# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alesya', '0004_auto_20180227_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationBinding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='alesya.Location', verbose_name='Child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='alesya.Location', verbose_name='Parent')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='locationbinding',
            unique_together=set([('child', 'parent')]),
        ),
    ]
