# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimized', models.ImageField(blank=True, max_length=5000, null=True, upload_to='images/')),
                ('origin', models.ImageField(max_length=5000, upload_to='images/')),
            ],
        ),
    ]
