# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField(verbose_name='Distance(meters)')),
                ('time', models.TimeField(verbose_name='Race time')),
                ('date', models.DateField(verbose_name='Race date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
